name: RecruitFlow CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------------
      # Setup Node
      # -------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # -------------------------
      # Install frontend
      # -------------------------
      - name: Install frontend dependencies
        working-directory: recruit-flow-front
        run: npm ci

      # -------------------------
      # Run Jest
      # -------------------------
      - name: Run frontend unit tests
        working-directory: recruit-flow-front
        run: npm run test -- --runInBand

      # -------------------------
      # Build Angular
      # -------------------------
      - name: Build Angular
        working-directory: recruit-flow-front
        run: npm run build -- --configuration production

      # -------------------------
      # Setup .NET
      # -------------------------
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # -------------------------
      # Start backend API
      # -------------------------
      - name: Start backend API
        working-directory: RecruitFlow.API
        run: |
          dotnet restore
          dotnet build
          dotnet run &

      # -------------------------
      # Run Cypress
      # -------------------------
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: recruit-flow-front
          start: npm start
          wait-on: |
            http://localhost:4200
            http://localhost:5072
          browser: chrome